#!/bin/bash
#
# Install-HopCharge-App.command
# ─────────────────────────────────────────────────────────────────
# Double-click this once. It builds a real macOS app called
# "HopCharge HR.app" on your Desktop. After that, you can drag the
# app anywhere (Desktop, Dock, Applications) and double-click it to
# launch the dashboard — it starts the server and opens your browser,
# then stops the server automatically when you quit the app.
#
# Requirements: Python 3 must already be installed (you already use it
# to run the dashboard). Nothing else is needed.
# ─────────────────────────────────────────────────────────────────

set -e

# The folder that contains app.py is the parent of this launcher folder.
LAUNCHER_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$LAUNCHER_DIR/.." && pwd)"

if [ ! -f "$PROJECT_DIR/app.py" ]; then
  echo "❌ Could not find app.py next to this installer."
  echo "   Keep this 'launcher' folder inside your resume_parser project folder."
  echo "   Looked in: $PROJECT_DIR"
  read -n 1 -s -r -p "Press any key to close."
  exit 1
fi

APP_NAME="HopCharge HR"
APP_PATH="$HOME/Desktop/$APP_NAME.app"

echo "▸ Project folder : $PROJECT_DIR"
echo "▸ Building app   : $APP_PATH"

# Clean any previous build
rm -rf "$APP_PATH"
mkdir -p "$APP_PATH/Contents/MacOS"
mkdir -p "$APP_PATH/Contents/Resources"

# ── 1. Build the .icns icon from the PNG ──────────────────────────
ICON_SRC="$LAUNCHER_DIR/appicon_1024.png"
if [ -f "$ICON_SRC" ]; then
  echo "▸ Generating icon…"
  ICONSET="$(mktemp -d)/HopCharge.iconset"
  mkdir -p "$ICONSET"
  for s in 16 32 64 128 256 512; do
    sips -z $s $s     "$ICON_SRC" --out "$ICONSET/icon_${s}x${s}.png"           >/dev/null 2>&1
    sips -z $((s*2)) $((s*2)) "$ICON_SRC" --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null 2>&1
  done
  iconutil -c icns "$ICONSET" -o "$APP_PATH/Contents/Resources/HopCharge.icns" 2>/dev/null || true
fi

# ── 2. Info.plist ─────────────────────────────────────────────────
cat > "$APP_PATH/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>HopCharge HR</string>
  <key>CFBundleDisplayName</key><string>HopCharge HR</string>
  <key>CFBundleIdentifier</key><string>com.hopcharge.hrdashboard</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>launch</string>
  <key>CFBundleIconFile</key><string>HopCharge</string>
  <key>LSMinimumSystemVersion</key><string>10.13</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST

# ── 3. The launcher executable ────────────────────────────────────
# It records the project path at build time so the app works from anywhere.
cat > "$APP_PATH/Contents/MacOS/launch" <<LAUNCH
#!/bin/bash
# HopCharge HR launcher — generated by the installer.
PROJECT_DIR="$PROJECT_DIR"
PORT=8000
URL="http://localhost:\$PORT"

cd "\$PROJECT_DIR" || {
  osascript -e 'display dialog "Could not find the dashboard project folder. It may have been moved." buttons {"OK"} with icon stop'
  exit 1
}

# Find a Python 3 interpreter.
# Prefer the python.org framework Python where the dashboard's packages are
# installed; this is the one the user runs successfully in VS Code.
PYBIN=""
PREFERRED="/Library/Frameworks/Python.framework/Versions/3.13/bin/python3"
if [ -x "\$PREFERRED" ]; then
  PYBIN="\$PREFERRED"
else
  # Fall back to any framework Python 3.x, newest first
  for fw in \$(ls -d /Library/Frameworks/Python.framework/Versions/*/bin/python3 2>/dev/null | sort -rV); do
    [ -x "\$fw" ] && PYBIN="\$fw" && break
  done
fi
# Last resort: whatever python3 is on PATH or in common locations
if [ -z "\$PYBIN" ]; then PYBIN="\$(command -v python3 || true)"; fi
if [ -z "\$PYBIN" ]; then
  for c in /usr/local/bin/python3 /opt/homebrew/bin/python3 /usr/bin/python3; do
    [ -x "\$c" ] && PYBIN="\$c" && break
  done
fi
if [ -z "\$PYBIN" ]; then
  osascript -e 'display dialog "Python 3 was not found. Please install Python 3, then try again." buttons {"OK"} with icon stop'
  exit 1
fi

# Is the server already running? (someone double-clicked twice)
if curl -s -o /dev/null "\$URL"; then
  open "\$URL"
  exit 0
fi

# Start the server in the background, log to the project folder
LOG="\$PROJECT_DIR/launcher_server.log"
"\$PYBIN" app.py > "\$LOG" 2>&1 &
SERVER_PID=\$!

# Wait up to ~20s for the server to answer, then open the browser
for i in \$(seq 1 40); do
  if curl -s -o /dev/null "\$URL"; then break; fi
  # if the server died early, surface the log
  if ! kill -0 \$SERVER_PID 2>/dev/null; then
    ERRTAIL="\$(tail -n 6 "\$LOG" 2>/dev/null | tr '"' "'" )"
    osascript -e "display dialog \"The dashboard failed to start.\n\nLast log lines:\n\$ERRTAIL\" buttons {\"OK\"} with icon stop"
    exit 1
  fi
  sleep 0.5
done

open "\$URL"

# Keep the app "running" (and the server alive) while the user works.
# A small dialog lets them stop the server cleanly. Closing it shuts down.
osascript <<'OSA'
display dialog "HopCharge HR Dashboard is running.

It opened in your browser at http://localhost:8000

Click \"Stop Dashboard\" when you are finished." buttons {"Stop Dashboard"} default button 1 with title "HopCharge HR" with icon note
OSA

# User clicked Stop (or closed) → shut the server down
kill \$SERVER_PID 2>/dev/null
# also clean up any stray uvicorn on the port
lsof -ti tcp:\$PORT 2>/dev/null | xargs kill 2>/dev/null || true
exit 0
LAUNCH

chmod +x "$APP_PATH/Contents/MacOS/launch"

# ── 4. Refresh icon cache & finish ────────────────────────────────
touch "$APP_PATH"
echo ""
echo "✅ Done!  '$APP_NAME.app' is on your Desktop."
echo "   • Double-click it to launch the dashboard."
echo "   • You can drag it into the Dock or Applications folder."
echo ""
echo "   First launch tip: if macOS says it's from an unidentified developer,"
echo "   right-click the app → Open → Open. You only need to do this once."
echo ""
read -n 1 -s -r -p "Press any key to close this window."
